name: flutter_modules_generator
description: A CLI tool to streamline and generate module structures for Flutter projects. This tool creates organized folder hierarchies and template files, including controllers, bindings, business logic, data models, services, and views. Designed to support both API and webview-based modules, it simplifies project setup and enforces a consistent code structure.
version: 1.0.5
repository: https://github.com/genss333/flutter_modules_generator.git

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  flutter_modules_generator: flutter_modules_generator.dart
