name: flutter_modules_generator
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/genss333/flutter_modules_generator.git

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
